/**:
  ros__parameters:

    inputs:
      sensor_names: ['camera_01_01', 'camera_02_01', 'camera_03_01', 'camera_04_01', 'radar_01_01',  'radar_02_01', 'radar_03_01','radar_04_01']
      camera_01_01:
        min_existence_probability: 0.7
        topic_name: '/perception/camera/camera_01_01/objects_transform'
      camera_02_01:
        min_existence_probability: 0.7
        topic_name: '/perception/camera/camera_02_01/objects_transform'
      camera_03_01:
        min_existence_probability: 0.7
        topic_name: '/perception/camera/camera_03_01/objects_transform'
      camera_04_01:
        min_existence_probability: 0.7
        topic_name: '/perception/camera/camera_04_01/objects_transform'
      radar_01_01:
        min_existence_probability: 0.7
        topic_name: '/perception/radar_01_01/tracks_transform_ros2'
      radar_02_01:
        min_existence_probability: 0.7
        topic_name: '/perception/radar_02_01/tracks_transform_ros2'
      radar_03_01:
        min_existence_probability: 0.7
        topic_name: '/perception/radar_03_01/tracks_transform_ros2'
      radar_04_01:
        min_existence_probability: 0.7
        topic_name: '/perception/radar_04_01/tracks_transform_ros2'
        
    operation_frame: 'layered_map_enu'

    euclidean_threshold: 12.0

    max_delay: 250.0

    roi:
      y_max: 500.0
      y_min: -500.0
      x_max: 500.0
      x_min: -500.0

    output:
      min_existence_probability: 0.7
      topic_name: '/perception/fusion/objects_t2t'

    use_sim_time: true

    debug_mode: false
