# The following map modes are supported:
# * lane - pass everything which is on or close to the lane
# * none - do not filter by map
# * (static) - behaves like lane
map_mode: "lane"

# The layered map classifier internally constructs a grid to conduct a 'point in region' lookup. This parameter
# specifies the grid size. If you have a large grid, you can increase this value
grid_resolution: 1.5

# The input topics of the node
ego_motion_topic: "/odometry_referenced_egomotion"
radar_tracking_sensor_0: "/sensor/radar_gen5/radar_locations_decoder_gen5/location_interface"
