###############################################
### Bosch Radar Gen5 Modulation Performance ###
###############################################

uint8 active_detection_measurement_program_id
uint16 active_modulation_id

float32 fov_distance_range_scaling_factor

# Distance
float32 distance_precision
float32 distance_seperability
float32 distance_minimum_value
float32 distance_maximum_value

# Velocity
float32 velocity_precision
float32 velocity_seperability
float32 velocity_minimum_value
float32 velocity_maximum_value

float32 distance_velocity_covariance
