##################################
### Bosch Radar Gen5 Blindness ###
##################################

# Number of detection threshold bins
uint16 num_bins_detection_threshold
bool num_bins_detection_thresold_valid

# Two-Target-Rate indicator
uint16 two_target_rate_indicator
bool two_target_rate_indicator_valid

# RCS model deviation for moving objects
uint16 rcs_moving_object_model_deviation_indicator
bool rcs_moving_object_model_deviation_indicator_valid

# Azimuth model deviation for moving objects
uint16 azimuth_moving_object_model_deviation
bool azimuth_moving_object_model_deviation_valid

# Azimuth model deviation for static objects
uint16 azimuth_static_object_model_deviation
bool azimuth_static_object_model_deviation_valid
