random_seed: 444

dataset:
  type: &dataset_type 'DAIR'
  batch_size: 6
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'   # 'proj' or 'anno'
  meanshape: False      # use predefined anchor or not
  writelist: ['car', 'van', 'truck', 'trailer','bus', 'pedestrian', 'cyclist', 'motorcyclist', 'barrow' ,'tricyclist'] #['Car', 'Pedestrian', 'Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  root_dir: '../data/'

model:
  type: 'monocon'
  backbone: 'dla34'
  neck: 'DLAUp'
  num_class: 10

optimizer:
  type: 'adam'
  lr: 0.00125
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [90, 120]

trainer:
  max_epoch: 260
  gpu_ids: 3, 1
  save_frequency: 5 # checkpoint save interval (in epoch)
  save_dir: './checkpoint/'
  resume_model: '/home/icv/Edward/inf_sense/src/camera/monocular_3d/infrastructure3dobjectdetection/baseline_methods/checkpoint/checkpoint_epoch_180.pth'


tester:
  type: *dataset_type
  mode: single   # 'single' or 'all'
  checkpoint: './checkpoint/checkpoint_epoch_140.pth'  # used for infrance
  checkpoints_dir: 'checkpoints'  # for 'all' model
  threshold: 0.2  # confidence filter
  save_dir: '../result'
